### ISSUE TITLE
Font size itemize

### ISSUE THREAD

**Issue by fschoner** [kylebutts/latex-templates#1]
Hi Kyle,

thanks a lot for the nice template. 

For some reason I'm unable to change the fontsize for the itemize environment. I've changed the preamble to 
```
%% itemize
\setbeamercolor{itemize item}{fg = accent!70!white}

% here is the only change
\setbeamerfont{itemize item}{size = \Huge}

\setbeamertemplate{itemize item}[circle]

\setbeamercolor{itemize subitem}{fg = accent!70!white}
\setbeamerfont{itemize subitem}{size = \small}
\setbeamertemplate{itemize subitem}[square]

\setbeamertemplate{itemize subsubitem}[square]
\setbeamercolor{itemize subsubitem}{fg = jet}
\setbeamerfont{itemize subsubitem}{size = \small}
```
but the only thing that changes is that the circle gets larger, not the font size. Any suggestions?

**Comment by kylebutts** [comment]
`\setbeamerfont{itemize item}` adjusts the font of the bullet, so you've correctly identified the problem. Two options for you:

1. You can change the environment one at a time by `{\Huge \begin{itemize} ... \end{itemize}}`

2. Put this in the preamble `\setbeamertemplate{itemize/enumerate body begin}{\Huge}`
