### ISSUE TITLE
Highlighting rows with a box in Beamer - Table contents move slightly

### ISSUE THREAD

**Issue by yukitakahashi1** [kylebutts/latex-templates#2]
Hi Kyle,

Thanks a lot for the nice templates!

For some reason, table contents move slightly when I highlight rows with a box in the Beamer template (please see pages 12-13 in the sample pdf in this repository). Is there any solution to this?

Thanks in advance!

**Comment by kylebutts** [comment]
Way too late, but I added a `\colorrow` option now
